language: bash
dist: stretch

env:
    - BACKEND=openssl-0.9.8e
    - BACKEND=openssl-1.0.1e
    - BACKEND=openssl-1.1.0h
    - BACKEND=openssl-1.1.1

install:
    - bash backends/$BACKEND.sh build

script:
    - bash verify.sh
